### ISSUE TITLE
following-sibling:: is not working

### ISSUE THREAD

**Issue by ducdev** [hieuvp/xpath-html#10]
Hi,

I'm playing around with `xpath-html` and I realized a possible issue.

```
const axios = require('axios')
const xpath = require('xpath-html')
const url = 'https://dev.to/'
 
axios.get(url)
  .then(res => {
    const node = xpath.fromPageSource(res.data).findElement("//a[contains(text(), 'Infinity')]/following-sibling::a")
    //     const node = xpath.fromPageSource(res.data).findElement("//a[contains(text(), 'Infinity')") // this one works well
    console.log(node)
  })
  .catch(console.error)
 ```

![image](https://user-images.githubusercontent.com/3524016/88485344-5faacc00-cf9f-11ea-99a6-18091a4b786d.png)

Could you please have a quick check to figure it out?

Thanks for making `xpath-html`!

**Comment by harrison-van** [comment]
Hello @ducdev,

Is your `res.data` an html page? better if you could log the content of your variable here.

Thank you!

**Comment by ducdev** [comment]
I think yes, you can try my code.
Basically, it's HTML of https://dev.to

**Comment by harrison-van** [comment]
You're right, this case is unexpectedly wrong.
If you found a way to solve this, please submit a PR.
Thank you for helping.

**Comment by cirosantilli** [comment]
Here's a more minimal reproduction:

```
#!/usr/bin/env node
const xpath = require("xpath-html");
let html = `<!doctype html>
<html lang=en>
<head>
<meta charset=utf-8>
<title>Min sane</title>
</head>
<body>
<div>aa</div>
<div>bb</div>
</body>
</html>`
console.log(xpath.fromPageSource(html).findElements("//div/following::div").length)
```

outcome:

```
/home/ciro/test/node_modules/xpath/xpath.js:1278
                                throw new Error("XPath parse error");
                                ^

Error: XPath parse error
    at XPathParser.parse (/home/ciro/test/node_modules/xpath/xpath.js:1278:11)
    at new XPathExpression (/home/ciro/test/node_modules/xpath/xpath.js:4287:17)
    at Object.exports.selectWithResolver (/home/ciro/test/node_modules/xpath/xpath.js:4735:19)
    at XPath.<anonymous> (/home/ciro/test/node_modules/xpath/xpath.js:4730:18)
    at XPath.findElements (/home/ciro/test/node_modules/xpath-html/src/XPath.js:48:24)
    at Object.<anonymous> (/home/ciro/test/html/main.js:18:40)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

xpath-html@1.0.2

And other simple nested queries appear broken too:

```
const xpath = require("xpath-html");
<html lang=en>
<head>
<meta charset=utf-8>
<title>Min sane</title>
</head>
<body>
<div><a>aa</a></div>
</body>
</html>`;
console.log(xpath.fromPageSource(html).findElements("//div//a[text()='aa']").length);
```

outputs 0 instead of the expected 1.

Going for the more raw reproduction with https://stackoverflow.com/a/25971812/895245 :

```
const xpath = require('xpath');
const parse5 = require('parse5');
const xmlser = require('xmlserializer');
const dom = require('xmldom').DOMParser;

function fromPageSource(html, xpathStr) {
  const document = parse5.parse(html);
  const xhtml = xmlser.serializeToString(document);
  const doc = new dom().parseFromString(xhtml);
  const select = xpath.useNamespaces({"x": "http://www.w3.org/1999/xhtml"});
  return select(xpathStr, doc);
}

let html = `<!doctype html>
<html lang=en>
<head>
<meta charset=utf-8>
<title>Min sane</title>
</head>
<body>
<div><a href="ab">aa</a></div>
</body>
</html>`;
console.log(fromPageSource(html, "//x:div//x:a").length);
```

then that works, note how you have to add the `x:` thing every time. So this is presumably why things fail on `following`, tested with:

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "test",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "parse5": "^6.0.1",
    "xmldom": "^0.4.0",
    "xmlserializer": "^0.6.1",
    "xpath": "0.0.32"
  }
}
```

So finally without this library I am able to use `following-siblint` it as:

```
<div><a href="ab">aa</a></div>
<div><a href="ab">aa</a></div>

console.log(fromPageSource(html, "//x:div//following-sibling::x:div").length);
```

which gives 1 hit as expected.
